"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Image from "next/image";


interface Props {
    qrUrl: string | null
    secret: string | null
    onStart: () => Promise<void> | void
    onVerify: (code: string) => Promise<void> | void
    onBack: () => void
}

export function AuthenticatorSetup({
    qrUrl,
    secret,
    onStart,
    onVerify,
    onBack,
}: Props) {
    const [step, setStep] = useState<"intro" | "qr" | "verify">("intro")
    const [code, setCode] = useState("")
    const [showSecret, setShowSecret] = useState(false)

    // STEP 1 – Intro
    if (step === "intro")
        return (
            <div className="max-w-md mx-auto space-y-6">
                <div className="space-y-3 text-sm text-muted-foreground">
                    <p>
                        Instead of waiting for text messages, get verification codes
                        from an authenticator app. It works even if your phone is offline.
                    </p>
                    <p>
                        First, download Google Authenticator from the Google Play Store
                        or the iOS App Store.
                    </p>
                </div>

                <Button
                    className="w-full"
                    onClick={async () => {
                        await onStart()
                        setStep("qr")
                    }}
                >
                    Set up
                </Button>

                <Button variant="ghost" className="w-full" onClick={onBack}>
                    Back
                </Button>
            </div>
        )

    // STEP 2 – QR
    if (step === "qr")
        return (
            <div className="max-w-md mx-auto space-y-6 text-center">
                <p className="text-sm">
                    Scan this QR code with your authenticator app.
                </p>

                {qrUrl && (
                    <div className="flex justify-center">

                        <Image
                            src={qrUrl}
                            alt="Authenticator QR code"
                            width={128}
                            height={128}
                            className="rounded"
                        />
                    </div>
                )}

                {secret && (
                    <div className="space-y-2">
                        <button
                            className="text-sm text-blue-600 hover:underline"
                            onClick={() => setShowSecret(!showSecret)}
                        >
                            Can’t scan it?
                        </button>

                        {showSecret && (
                            <div className="bg-muted text-foreground border rounded-md p-4 font-mono text-sm break-all">
                                {secret}
                            </div>
                        )}
                    </div>
                )}

                <Button
                    className="w-full"
                    onClick={() => setStep("verify")}
                >
                    Next
                </Button>

                <Button
                    variant="ghost"
                    className="w-full"
                    onClick={onBack}
                >
                    Back
                </Button>
            </div>
        )

    // STEP 3 – Verify
    return (
        <div className="max-w-md mx-auto space-y-6">
            <p className="text-sm text-muted-foreground">
                Enter the 6-digit code generated by your authenticator app.
            </p>

            <Input
                value={code}
                onChange={(e) => setCode(e.target.value)}
                placeholder="000000"
                maxLength={6}
                className="text-center tracking-widest text-lg"
            />

            <Button
                className="w-full"
                onClick={async () => {
                    await onVerify(code)
                    setCode("")
                }}
            >
                Verify
            </Button>

            <Button
                variant="ghost"
                className="w-full"
                onClick={onBack}
            >
                Back
            </Button>
        </div>
    )
}